/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package animalfoster;

import javax.swing.JFrame;

/**
 *
 * @author Asus
 */
public class AccessedHelp extends javax.swing.JFrame {

    /**
     * Creates new form AccessedHelp
     */
    public AccessedHelp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Minimize = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        GetInvolved = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        help = new javax.swing.JLabel();
        OurTeam = new javax.swing.JLabel();
        HomePage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("<html>\nE-mail: fosterparadise@gmail.com<br>\nContact: 01311768602</html>");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 700, 380, 80));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("<html><h1>Our Motive</h1>\nFrom dogfighting to fake animal rescue videos and monkey torture, animal cruelty is becoming an increasingly popular form of entertainment. Foster Paradise Team is exposing these cruel and illegal activities through undercover operations and investigative reports.\nOur team has found hundreds of accounts and thousands of posts on social media platforms that promote animal cruelty, despite these posts being against these platforms’ community standards.<br>\n\n<h1>About Us</h1>\nOur mission is to create a better world for animals<br>\n-We end the needless suffering of animals<br>\n-We influence decision makers to put animals on the global agenda<br>\n-We help the world see how important animals are to all of us<br>\n-We inspire people to change animals’ lives for the better<br>\n-We move the world to protect animals<br>\n\n<h1>Equity, diversity and Inclusion</h1>\nFoster Paradise believes that our success depends on a culture that values and celebrates equity, diversity and inclusion in our people, to achieve our vision to end cruelty and suffering to animals, forever.  As an equal opportunity employer, we are committed to creating a diverse and inclusive working environment, empowering all our people to achieve their potential. We actively celebrate diversity of our people and while we have some way to go, we are committed to ensuring all our people are heard and feel included. We will not rest until we achieve equity and equality of opportunity for all our people.<br>\n\n\n</html>");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1500, 630));

        Minimize.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Minimize.setForeground(new java.awt.Color(204, 204, 204));
        Minimize.setText("-");
        Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
        });
        jPanel1.add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 10, 10, 10));

        Exit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Exit.setForeground(new java.awt.Color(204, 204, 204));
        Exit.setText("X");
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 10, 10, -1));

        GetInvolved.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        GetInvolved.setForeground(new java.awt.Color(255, 255, 255));
        GetInvolved.setText("Get Involved");
        GetInvolved.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GetInvolved.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GetInvolvedMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GetInvolvedMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                GetInvolvedMousePressed(evt);
            }
        });
        jPanel1.add(GetInvolved, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("E-mail  Us");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 30, -1, -1));

        help.setForeground(new java.awt.Color(204, 0, 0));
        help.setText("Help?");
        help.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpMouseClicked(evt);
            }
        });
        jPanel1.add(help, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 40, -1, -1));

        OurTeam.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        OurTeam.setForeground(new java.awt.Color(255, 255, 255));
        OurTeam.setText("Our Team");
        OurTeam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OurTeam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OurTeamMouseClicked(evt);
            }
        });
        jPanel1.add(OurTeam, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, 110, 30));

        HomePage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/animalfoster/FosterLogo.png"))); // NOI18N
        HomePage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomePage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomePageMouseClicked(evt);
            }
        });
        jPanel1.add(HomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 113));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 116, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/animalfoster/Background3.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 1540, 820));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeMouseClicked

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void GetInvolvedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GetInvolvedMouseClicked
        // TODO add your handling code here:
        dispose();
        LogOut lp = new LogOut();
        lp.setVisible(true);
        lp.pack();
        lp.setLocationRelativeTo(null);
        lp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_GetInvolvedMouseClicked

    private void GetInvolvedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GetInvolvedMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_GetInvolvedMouseEntered

    private void GetInvolvedMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GetInvolvedMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_GetInvolvedMousePressed

    private void helpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMouseClicked
        // TODO add your handling code here:
        dispose();
        AccessedHelp ah = new AccessedHelp();
        ah.setVisible(true);
    }//GEN-LAST:event_helpMouseClicked

    private void OurTeamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OurTeamMouseClicked
        // TODO add your handling code here:
        dispose();
        OurTeam ot = new OurTeam();
        ot.setVisible(true);
    }//GEN-LAST:event_OurTeamMouseClicked

    private void HomePageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomePageMouseClicked
        // TODO add your handling code here:
        dispose();
        AccessedFrontDisplay afd = new AccessedFrontDisplay();
        afd.setVisible(true);
    }//GEN-LAST:event_HomePageMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        Email sa = new Email();
        sa.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccessedHelp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccessedHelp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccessedHelp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccessedHelp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccessedHelp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel GetInvolved;
    private javax.swing.JLabel HomePage;
    private javax.swing.JLabel Minimize;
    private javax.swing.JLabel OurTeam;
    private javax.swing.JLabel help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
